# 5. Cross-Validation

## 5.1 Problem Setting

In the first notebook `1_eda.ipynb`, we saw in Section 1.5 that the data is not independent, so consecutive rows are correlated since they all belong to the same game. The solution suggested in the following Section 1.6 is to sample games by groups or chunks of 100 games (which is the approximate size of positions observed in the corresponding graphs). This comes into play when actually splitting the data into train and test datasets, which is correctly done using cross-validation.

Very conveniently, the `sklearn` library already has a cross-validation class `GroupKFold` which implements the desired behavior.

## 5.2 Method

Since cross-validation has to do with the training, predicting and testing of the models, we will include `cross_validate` method to our `ModelManager` class which, given a `DataManager` and other parameters implements the cross-validation and outputs the results, including the metric and time for fitting and predicting.

One parameter we want to be able to tweak is `game_len`, which we will leave at the default value of 100 as predicted previously. We will also pass the scoring metric and number of folds.

Another problem which may arise is unbalanced representation in each fold. If we split the data by chunks of 100 (or supposed games), it can happen that entire games which are biased towards the white or black pieces end up in the same folds. A possible solution would be to define a stratified version for our problem, by choosing a custom class for each group and then splitting accordingly. An alternative and rather simple solution would be to also group games and suppose that since the entire dataset is balanced, each game group will also be balanced.

## 5.3 Testing

Let's see an example of how to use the cross-validation method we have implemented with a simple Gradient Boosting model.

In [2]:
from chess_eval import *

sm = StorageManager()
sm.list_models()

,Name,Model,Dataset,Notes
0,GBR_one,GradientBoostingRegressor,one,
1,mlpr_one,MLPRegressor,one,
2,MLPR_100k_rd,MLPRegressor,chessData,use FENMaterial64 transformer

In [3]:
mm, dm = load_model("GBR_one")

In [4]:
results, summary = mm.cross_validate(dm)  # ~1 minute
summary

,train_score_mean,train_score_std,test_score_mean,test_score_std,train_time_mean,test_time_mean
0,0.518036,0.001049,0.50663,0.005837,52.360734,0.150027