In [1]:
from chess_eval import *
sm = StorageManager()

In [4]:
sm.list_datasets()

,Name,Shape,Notes
0,temp,"[10000, 18]",
1,20251125230028,"[10000, 18]",
2,123456789,"[10000, 18]",
3,full,"[9683, 84]",
4,allF_1M_100k,"[100000, 84]",features: 82\nread_size=1_000_000\nsample_size...
5,one,"[100000, 84]",

In [3]:
sm.list_models()

                       Model    Dataset             Notes
0  GradientBoostingRegressor  chessData
1  GradientBoostingRegressor  chessData  df: allF_1M_100k
2  GradientBoostingRegressor        one           df: one